###########
# site.title

title: emil jermann
description: My brain, and other things
# baseurl: "/jekyllBear" # the subpath of your site, e.g. /blog/
url: "https://emiljermann.com" # the base hostname & protocol for your site
# host: 0.0.0.0
email: emil.j.jermann@gmail.com
author: Emil Jermann
GitHub: https://github.com/emiljermann


#########################
# more settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# sass:
#   sass_dir: css
#   style:    compressed

collections:
  projects:
    output: true
    permalink: /projects/:path/
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# baseurl: ""
permalink: /blog/:slug
timezone: America/New_York
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

# Pages
Blog: /blog
About: /about

Resume: /assets/emiljermann_resume.pdf

# Add general links to site pages here
links:
  
  

# Add links for more focus here
special_links:
  # "Search": https://duckduckgo.com